on:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install -r requirements.txt
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: ./new_agenda.py